apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 15672
    name: management
  - port: 5672
    name: main
  clusterIP: None
  selector:
    app: rabbitmq
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
      #annotations:
      #  pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: ${SERVICE_NAME}
        image: ' '
        imagePullPolicy: Always
        ports:
        - containerPort: 15672
          protocol: TCP
          name: management
        - containerPort: 5672
          protocol: TCP
          name: main
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/rabbitmq
        # readinessProbe:
        #   exec:
        #     command:
        #     - /usr/share/container-scripts/rabbitmq/readiness-probe.sh
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 5
        env:
          - name: RABBITMQ_NODENAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
volumeClaimTemplates:
- metadata:
    name: datadir
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi
