apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: amazeeio-openshift-template-node
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_SITEGROUP
    description: Which sitegroup this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: SITEGROUP
    description: Which sitegroup this belongs to, original value
    required: true
  - name: AMAZEEIO_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: ROUTER_URL
    description: URL of the Router
    required: true
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    name: rabbitmq
    labels:
      app: rabbitmq
  spec:
    clusterIP: None
    ports:
    - port: 15672
      name: management
    - port: 5672
      name: main
    selector:
      app: rabbitmq
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: rabbitmq
  spec:
    serviceName: "rabbitmq"
    replicas: 3
    template:
      metadata:
        labels:
          app: rabbitmq
        #annotations:
        #  pod.alpha.kubernetes.io/initialized: "true"
      spec:
        containers:
        - name: ${SERVICE_NAME}
          image: rtprio/rmq-cluster
          imagePullPolicy: Always
          ports:
          - containerPort: 15672
            protocol: TCP
            name: management
          - containerPort: 5672
            protocol: TCP
            name: main
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/rabbitmq
            - name: logdir
              mountPath: /var/log/rabbitmq
          readinessProbe:
            exec:
              command:
              - /usr/lib/rabbitmq/bin/rabbitmqctl
              - node_health_check
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: CLUSTERED
              value: "true"
            - name: CLUSTER_WITH
              value: "rabbitmq-0@rabbitmq-0.${SAFE_SITEGROUP}.svc.cluster.local"
            - name: ERLANG_COOKIE
              value: "0d599f0ec05c3bda8c3b8a68c32a1b47"
            - name: RABBITMQ_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
    volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        # storageClassName: my-storage-class
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: logdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        # storageClassName: my-storage-class
        resources:
          requests:
            storage: 1Gi
